### ISSUE TITLE
Status is always true

### ISSUE THREAD

**Issue by ewal** [SudoPlz/react-native-connectivity-tracker#1]
xcode 10
ios 12
react-native 0.56

Hi, I have only tested in ios simulator but only get a connectivity notification change when status is or goes back online. So status is always true in my case.

**Comment by SudoPlz** [comment]
I'll test and post back, thank you.

**Comment by SudoPlz** [comment]
I think the problem is that you're testing on an iOS simulator, can you try on a real device?
That should clear things up.

Can you try and let me know if it works fine on your device?

**Comment by SudoPlz** [comment]
On my end it works well on the device but not on the simulator.
